speller:
	/usr/bin/gcc -std=c11 -Wextra -Wall -Wshadow -Wsign-compare -g3 -c -o speller.o speller.c
	/usr/bin/gcc -std=c11 -Wextra -Wall -Wshadow -Wsign-compare -g3 -c -o dictionary.o dictionary.c
	/usr/bin/gcc -std=c11 -Wextra -Wall -Wshadow -Wsign-compare -g3 -g -g0 -o speller speller.o dictionary.o -lm
